input {
  beats {
    port => 5044
  }
}

filter {
  if [log][file][path] =~ "auth.log" {
    mutate {
      add_tag => ["auth_log", "zero_trust_monitoring"]
    }
  }

  if "Failed password" in [message] {
    mutate {
      add_tag => ["failed_login", "security_incident"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "zero-trust-security-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
